jobs:
  - job: RunTests
    strategy:
      matrix:
        GoVersion_1_13:
          go.version: '1.13'
        GoVersion_1_14:
          go.version: '1.14'

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: echo ${{ parameters.os }}

      - template: ../steps/setup_go.yml
        parameters:
          goVersion: '$(go.version)'

      - template: ../steps/format_go.yml

      - ${{ if eq(parameters.os, 'linux') }}:
        - template: ../steps/install_tiledb_linux.yml

      - ${{ if eq(parameters.os, 'macos') }}:
        - template: ../steps/install_tiledb_macos.yml

      - script: |
          set -e -x
          go version
          go get -u github.com/jstemmer/go-junit-report
          go get github.com/axw/gocov/gocov
          go get github.com/AlekSi/gocov-xml
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
          curl https://cdn.shiftleft.io/download/sl > $(go env GOPATH)/bin/sl && chmod a+rx $(go env GOPATH)/bin/sl
        displayName: 'Install Dependencies'

      - ${{ if eq(parameters.os, 'linux') }}:
        - script: |
            set -e -x
            golangci-lint run
          displayName: 'Run Code Quality Checks'

      - script: |
          set -v -x
          go test -v -coverprofile=coverage.txt -covermode count ./... > test_results.txt
          go-junit-report < test_results.txt > report.xml
        displayName: 'Run Unit Tests'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testRunner: JUnit
          testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml

      - script: |
          set -e -x
          gocov convert coverage.txt > coverage.json
          gocov-xml < coverage.json > coverage.xml
        displayName: 'Run Code Coverage Tests'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml